---
title: ''
output: html_document
---

# Bayesian Structural Time Series Level 1: What is BSTS?


### Introduction

In this tutorial we introduce *Bayesian Structural Time Series* models based on the paper [Prediction the Present with Bayesian Structural Time Series](http://www.inderscience.com/offer.php?id=59942) by Steven L. Scott and Hal Varian. We will illustrate how BSTS can be implemented using the R package [bsts](https://cran.r-project.org/web/packages/bsts/index.html). But before we can do that, we need to lern about *structural time series models*.


### Structural Time Series Models

In this section we provide an overview of structural time series models, a.k.a. state space time series models. Note that we do not enter the Bayesian context yet. Here, we consider structural models from the classical perspective.

In structural time series modeling, we consider our data to come from some unobserverd process called the *state space* and attempt to model this latent state. The data we observe is generated by this state space, but with added noise. The simplest model is called the *local level model*. The equations for this model are as follows:

\begin{align}
y_t &= \mu_t + \varepsilon_t  &\varepsilon_t \sim N(0,\sigma^2_{\varepsilon}) \\
\mu_{t+1} &= \mu_t + \xi_t  &\xi_t \sim N(0, \sigma^2_{\xi}) \nonumber
\end{align}

Here, $t = 1,2,\ldots, n$ is the time index and $\mu_t$ is our latent state, the unobserved level at time $t$. The are two sources of error here, $\varepsilon_t$ and $\xi_t$. These correspond to error in the level, $\xi_t$, and the error due to observation, $\varepsilon_t$.

This model estimates the series by considering only the level of the series at each time point. We can think of this as analogous to the inercept in linear regression but allowing for the intercept to vary over time.

More generally, a state space model looks like this:

\begin{align}
y_t &= Z_t^T \alpha_t + \varepsilon_t  &\varepsilon_t \sim N(0, H_t) \\
\alpha_{t+1} &= T_t \alpha_{t} + R_t \eta_t  &\eta_t \sim N(0,Q_t)
\end{align}

But what do these fancy equations mean? Well, the first equation is caled the *observation equation*. It tells us how our observed time series $y_t$ is related to the (unobserved) state $\alpha_t$. The second equation is called the *transition equation* and it describes how the state $\alpha_t$ transitions at each time point. What are $Z_t, T_t$, and $R_t$? They can be fixed design matrices, contain model parameters, or both. This allows for a lot of flexibility and allows us to describe a wide class of models. Fun fact: ARIMA models are special cases of structural models. Those greek letters on the right are error terms.



