---
title: "Adventures in Bayesian Structural Time Series"
subtitle: "Part 2: Structural Time Series"
author: "Andrew Bates, Josh Gloyd, Tyler Tucker"
urlcolor: blue
header-includes:
  - \usepackage{themes/beamerthemednd}
output: beamer_presentation
#theme: 'dnd'
#colortheme: 'dndcolors'
#fonttheme: 'dndfonts'
---



## Outline

> - Structural Time Series Models:
>     - Local level model
>     - Local linear trend model
>     - Models with seasonal component
>     - Models with regression component

<!-- new slide -->

## Structural Time Series 

> - Also called State Space Models
> - Data comes from unobserved variable called the  **state space**
> - We model the state space instead of the observed data directly


<!-- new slide-->

## Structural Time Series

### Local Level Model

- $y_t$: observed data
- $\mu_t$: unobserved state

\begin{align*}
y_t &= \mu_t + \varepsilon_t  &\varepsilon_t \sim N(0,\sigma^2_{\varepsilon}) \\
\mu_{t+1} &= \mu_t + \xi_t  &\xi_t \sim N(0, \sigma^2_{\xi}) 
\end{align*}


<!-- new slide -->

## Local Level Model

- will have plot here


<!-- new slide -->

## Structural Time Series

### Local Linear Trend Model

- $y_t, \mu_t$: same as before
- $\nu_t$: slope (additional state component)

\begin{align*}
y_t &= \mu_t + \varepsilon_t  &\varepsilon_t \sim N(0, \sigma_{\varepsilon}^2) \\
\mu_{t+1} &= \mu_t + \nu_t + \xi_t  &\xi_t \sim N(0, \sigma_{\xi}^2) \\
\nu_{t+1} &= \nu_t + \zeta_t  &\zeta_t \sim N(0, \sigma_{\zeta}^2)
\end{align*}

<!-- new slide -->

## Local Linear Trend Model

- will have picture here


<!-- new slide -->

## Structural Time Series

### Local Trend With Seasonality

- $\mu_t$: local linear trend
- $\tau_t$: seasonal component
    - $S$ dummy variables (1 for each season)

\begin{align*}
&y_t = \mu_t + \tau_t + \varepsilon_t  &\zeta_t \sim N(0, \sigma^2_{\varepsilon}) \\
&\tau_t = \sum_{s=1}^{S-1} \tau_{t-s} + \omega_t  &\tau_t \sim N(0, \sigma^2_{\omega})
\end{align*}


<!-- new slide -->

## Local Trend With Seasonality

- will have picture here


<!-- new slide -->

## Structural Time Series

### Local Trend With Regression

- $\mu_t$: local linear trend 
- $\tau_t$: seasonal component
- $\beta_t^Tx_t$: regression component

\begin{align*}
&y_t = \mu_t + \tau_t + \beta_t^Tx_t  + \varepsilon_t &\varepsilon_t \sim N(0, \sigma^2_{\varepsilon})
\end{align*}


<!-- new slide-->


## Structural Time Series

- (1): observation equation
- (2): transition equation

### General Form

- $y_t$: data
- $\alpha_t$: state component

\begin{align}
y_t &= Z_t'\alpha_t + \varepsilon_t  &\varepsilon_t \sim N(0, H_t)  \\
\alpha_{t+1} &= T_t\alpha_t + R_t\eta_t  &\eta_t \sim N(0, Q_t) 
\end{align}







