---
title: "Adventures in Bayesian Structural Time Series"
subtitle: "Part 3: Analyzing SST Data"
author: "Andrew Bates, Josh Gloyd, Tyler Tucker"
urlcolor: blue
header-includes:
  - \usepackage{themes/beamerthemednd}
output: 
  beamer_presentation:
    incremental: true
#theme: 'dnd'
#colortheme: 'dndcolors'
#fonttheme: 'dndfonts'
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(fig.align = 'center', out.width = '95%',
                      message = FALSE, cache = TRUE)
```


<!-- slide 3 -->

## Outline

- SST Data

- Use `bsts` for
    - Fit
        - local level
        - local linear trend model
        - local trend with seasonality
    - Posterior distribution
    - Forecast
    - Model Comparison
    
<!-- slide 4 -->
    
## SST Data

- Sea Surface Temperature near Gibraltar
- Collected every 12 days
- January 2004 to November 2017
- Obtained from [Argovis](http://argovis.com/map)

    
<!-- slide 5 -->

## SST Data

```{r, echo = FALSE}
library(readr)
library(bsts) # also loads BoomSpikeSlab, Boom, MASS, zoo, xts


gilbralter <- read_csv("data/gilbraltersimple.csv")
gilt <- ts(gilbralter$tempMean, start=c(2004,1,13),
           end=c(2017, 11, 25), frequency=30)
plot(gilt, main='SST of Gilbralter region',
     xlab='Date',
     ylab='Temperature (C)')
```


<!-- slide 6 -->

## Setup

```{r, eval = FALSE}
library(readr)
library(bsts) 
# bsts also loads BoomSpikeSlab, Boom, MASS, zoo, xts


gilbralter <- read_csv("data/gilbraltersimple.csv")
gilt <- ts(gilbralter$tempMean, start=c(2004,1,13),
           end=c(2017, 11, 25), frequency=30)
plot(gilt, main='SST of Gilbralter region',
     xlab='Date',
     ylab='Temperature (C)')
```


