---
title: "Adventures in Bayesian Structural Time Series"
subtitle: "Part 3: Structural Time Series in Bayesian Context"
author: "Andrew Bates, Josh Gloyd, Tyler Tucker"
urlcolor: blue
header-includes:
  - \usepackage{themes/beamerthemednd}
output: 
  beamer_presentation:
#theme: 'dnd'
#colortheme: 'dndcolors'
#fonttheme: 'dndfonts'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Outline

> - Without Regression:
>      - Prior
>      - Posterior
> - With Regression:
>      - Prior
>      - Posterior
     
<!-- slide 3 -->

## Without Regression

> - Prior
>     - Specify distribution on parameters (variances)
> - Posterior
>     - Kalman filter and Kalman smoother
>     - Markov Chain Monte Carlo


<!-- slide 4 -->


## Spike and Slab Prior

> - Consider regression coefficients fixed through time
>     - If not, include as state variables
> - **Spike**: prior for probability of regression coefficients being zero
> - **Slab**: prior on nonzero regression coefficients and variance

<!-- slide 5 -->

## Spike and Slab Prior

### Spike

- $\gamma_k = 1$ if $\beta_k \neq 0$. $\gamma_k = 0$ if $\beta_k = 0$
- $\beta_{\gamma}$: subset of $\beta$s with $\beta_k \neq 0$
- Independent Bernoulli prior:
\[\gamma \sim \prod_{i=1}^K \pi_k^{\gamma_k} (1-\pi_k)^{1-\gamma_k}\]


<!-- slide 6 -->


## Spike and Slab Prior

### Slab

- $\Omega^{-1}$: symmetric matrix
    - $\Omega_{\gamma}^{-1}$: submatrix corresponding to $\gamma_k = 1$
- Conjugate prior:
\begin{align*}
&\beta_{\gamma}\big|\sigma_{\varepsilon}^2, \gamma \sim N(b_{\gamma}, \sigma_{\varepsilon}^2\Omega_{\gamma}) 
& \frac{1}{\sigma_{\varepsilon}^2}\big|\gamma \sim \mathrm{Gamma}\left(\frac{v}{2}, \frac{ss}{2}\right)
\end{align*}


<!-- slide 7 -->


## Spike and Slab Prior

### Full Prior

\[ p(\beta, \gamma, \sigma_{\varepsilon}^2) = p(\beta_{\gamma}|\gamma, \sigma_{\varepsilon}^2)p(\sigma_{\varepsilon}^2|\gamma)p(\gamma)\]


<!-- slide 8 -->

## Specifying the Prior

> - $ss$, $v$: prior sum of squares and prior sample size
>     - Expected $R^2$, expected model size
> - $\pi_k$: inclusion probability for regression coefficients
> - $\Omega^{-1}$: based on design matrix $X$
>     - $\Omega^{-1} = \frac{k}{n}X^TX$


<!-- slide 9 -->


## Spike and Slab Posterior

### Posterior of $\beta$ and $\sigma_{\varepsilon}^2$ given $\gamma, y^*$

- $Z_t^*$: observation matrix $Z_t$ with $\beta^Tx_t = 0$
- $y_t^* = y_t - Z_t^{*^T}\alpha_t$
- $y^* = (y_1^*, y_2^*, \ldots, y_n^*)^T$

- \begin{align*}
&\beta_{\gamma}\big|\sigma_{\varepsilon}, \gamma, y^* \sim N(\tilde{\beta}_{\gamma}, \sigma_{\varepsilon}^2V_{\gamma})
& \frac{1}{\sigma_{\varepsilon}^2}\big|\gamma,y^* \sim \mathrm{Gamma}\left(\frac{N}{2}, \frac{SS_{\gamma}}{2}\right)
\end{align*}
- $V_{\gamma}^{-1} = (X^TX)_{\gamma} + \Omega_{\gamma}^{-1}$
- $\tilde{\beta}_{\gamma} = V_{\gamma}(X_{\gamma}^Ty^* + \Omega_{\gamma}^{-1} b_{\gamma})$
- $N = v + n$
- $SS_{\gamma} = ss + y^{*^T} y^* + b_{\gamma}^T\Omega_{\gamma}^{-1}b_{\gamma} - \tilde{\beta}_{\gamma}^TV_{\gamma}^{-1}\tilde{\beta}_{\gamma}$


<!-- slide 10 -->

## Spike and Slab Posterior

### Posterior of $\gamma$ given $y^*$:
\[\gamma\big|y^* \sim C(y^*) \frac{|\Omega_{\gamma}^{-1}|^{1/2}}{|V_{\gamma}^{-1}|^{1/2}} \frac{p(\gamma)}{SS_{\gamma}^{N/2 - 1}}\]


<!-- slide 11 -->

## Posterior Sampling

- Combination of:
    - stochastic Kalman smoother
    - MCMC:
        - stochastic search variable selection
        - Gibbs sampler
